development:
  bucket: emotionpilates
  access_key_id: AKIAJZKYLJZUVBUGCMFA
  secret_access_key: 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
test:
  bucket: emotionpilates
  access_key_id: AKIAJZKYLJZUVBUGCMFA
  secret_access_key: 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
production:
  bucket: emotionpilates
  access_key_id: AKIAJZKYLJZUVBUGCMFA
  secret_access_key: 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

